[package]
name = "keyrs"
version = "0.1.3"
edition = "2024"
description = "A library for reading key events from a keyboard"
license = "MIT"

[dependencies]
async-trait = "0.1.92"
evdev = { version = "0.13.2", features = ["tokio"] }
tokio = { version = "1.53", features = ["macros", "rt", "sync", "time"] }
tokio-util = "0.7.19"
tracing = "0.1.44"

[dev-dependencies]
tokio = { version = "1.53", features = ["rt-multi-thread"] }
tracing-subscriber = "0.3.23"
